# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "create ipa"
  lane :create_ipa do

    sigh(
      force: false,
      app_identifier: "org.reactjs.native.example.FastlaneWithFabric",
      adhoc: true,
    )

    increment_version_number(
      version_number: "0.0.0",
      xcodeproj: "FastlaneWithFabric.xcodeproj"
    )

    increment_build_number(
      build_number: Time.now.strftime("%Y%m%d%H%M"),
      xcodeproj: "FastlaneWithFabric.xcodeproj"
    )

    build_app(
      scheme: "FastlaneWithFabric",
      output_name: "FastlaneWithFabric.ipa",
      export_method: "ad-hoc"
    )

  end

  desc "deploy fabric"
  lane :fabric do

    crashlytics(
      crashlytics_path: "./Crashlytics.framework",
      api_token: ENV["FABRIC_API_TOKEN"],
      build_secret: ENV["FABRIC_API_SECRET"],
      ipa_path: 'FastlaneWithFabric.ipa',
      notes: "by fastlane",
      notifications: true,
      groups: ENV["FABRIC_GROUP"],
    )

  end

  desc "deploy appetize"
  lane :to_appetize do
    xcbuild(
      scheme: "FastlaneWithFabric",
    )

    sh("zip", "-r", "-X", "../app.zip", ENV["HOME"] + '/Library/Developer/Xcode/DerivedData/'+ ENV["APP_NAME"] +"/Build/Products/Release-iphonesimulator/FastlaneWithFabric.app")

    appetize(
      path: "./app.zip",
      platform: "ios",
      api_token: ENV["APPETIZE_TOKEN"],
      public_key: ENV["APPETIZE_PUBLIC_KEY"],
    )

    slack(
      message: ENV["SLACK_USERNAME"],
      message: "new build available #{lane_context[SharedValues::APPETIZE_APP_URL]}",
      link_names: true
    )

  end

end
